### ISSUE TITLE
Slice a csv file without loading it in memory

### ISSUE THREAD

**Issue by Mullefa** [hadley/fastread#54]
Would it be possible to have a `lines` argument to the `read_csv()` file which lets the user specify which lines to load into memory? This would be used if the not all the data is needed and either: the file is taking a long time to read into memory, or there is not enough memory to hold the file. 

Some pseudo code which hopefully illustrates the request:

```R
library(fastread)
library(dplyr)

file_path <- 'path/to/very/large/csv/file.csv'

# with the updated API
df <- file_path %>%
  read_csv(lines = sample(count_lines(file_path), 1e5))

# equivalent to
df <- file_path %>%
  # this function call takes a long time and could throw
  read_csv() %>%
  sample(1e5)
```

**Comment by Ironholds** [comment]
It already does that, surely? The <code>...</code> which passes through to build_delim_spec, which includes the arguments <code>n</code> and <code>skip</code>.

**Comment by Mullefa** [comment]
I don't see how I'd achieve what I want using these two arguments. For example, with the current API, how would I read the lines whose indices were even: `2, 4, 6, ...`?

**Comment by hadley** [comment]
This is something we'll consider for the future. It's hard to know how far to go - should we implement a handful of special cases like this, or develop a dplyr backend for out-of-memory data?

**Comment by Mullefa** [comment]
dplyr backend for out of memory data ;) ?

**Comment by Mullefa** [comment]
Btw, my request was motivated by the following: I downloaded the `train` data set from [here](https://www.kaggle.com/c/avazu-ctr-prediction/data) to do some more work on modelr. Its a csv with about ~ 40 million rows; I'm not sure if R currently has a good way of reading in a random subset of this data...

**Comment by hadley** [comment]
How much memory do you have? That's the easiest answer for now.

**Comment by unikum** [comment]
> dplyr backend for out of memory data ;) ?

as backend for `ff` package may be.

**Comment by hadley** [comment]
@unikum I've looked at ff with an eye to this, and it's not obvious it's a good fit.
